-- MySQL Script generated by MySQL Workbench
-- Fri Nov  1 08:49:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Escola` ;

-- -----------------------------------------------------
-- Schema Escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escola` DEFAULT CHARACTER SET utf8 ;
USE `Escola` ;

-- -----------------------------------------------------
-- Table `Escola`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola`.`Usuarios` (
  `nomeUsoario` INT NOT NULL,
  `senha_Usuario` VARCHAR(7) NULL,
  PRIMARY KEY (`nomeUsoario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola`.`Turma` (
  `codTurma` INT NOT NULL AUTO_INCREMENT,
  `NomeTurma` VARCHAR(45) NOT NULL,
  `PeriodoTurma` DATE NULL,
  `Usuarios_nomeUsoario` INT NOT NULL,
  PRIMARY KEY (`codTurma`, `Usuarios_nomeUsoario`),
  INDEX `fk_Turma_Usuarios_idx` (`Usuarios_nomeUsoario` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Usuarios`
    FOREIGN KEY (`Usuarios_nomeUsoario`)
    REFERENCES `Escola`.`Usuarios` (`nomeUsoario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escola`.`Atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escola`.`Atividades` (
  `idAtividades` INT NOT NULL AUTO_INCREMENT,
  `nomeatividades` VARCHAR(45) NULL,
  `dataEntrega` DATE NULL,
  `pesoAtividades` INT NULL,
  `Turma_codTurma` INT NOT NULL,
  `Turma_Usuarios_nomeUsoario` INT NOT NULL,
  PRIMARY KEY (`idAtividades`, `Turma_codTurma`, `Turma_Usuarios_nomeUsoario`),
  INDEX `fk_Atividades_Turma1_idx` (`Turma_codTurma` ASC, `Turma_Usuarios_nomeUsoario` ASC) VISIBLE,
  CONSTRAINT `fk_Atividades_Turma1`
    FOREIGN KEY (`Turma_codTurma` , `Turma_Usuarios_nomeUsoario`)
    REFERENCES `Escola`.`Turma` (`codTurma` , `Usuarios_nomeUsoario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
